Repository hmcts/wa-workflow-api, pull requests merged in 2021-08, with the labels that each got.

#269 upgrade both springboot and Chart versions
  build.gradle
  charts/wa-workflow-api/Chart.yaml
  charts/wa-workflow-api/values.preview.template.yaml
  charts/wa-workflow-api/values.yaml
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/Application.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/idempotency/IdempotencyTaskWorkerHandler.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootIntegrationBaseTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-269

#274 CVE-2021-28170
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-274

#272 Added FT stage to nightly build
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-272

#271 RWA-452 Implement Provider Contract/Pact Test - POST /workflow/message
  Jenkinsfile_CNP
  README.md
  build.gradle
  docker-pactbroker-compose.yml
  src/contractTest/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootContractBaseTest.java
  src/contractTest/java/uk/gov/hmcts/reform/waworkflowapi/consumer/wa/WorkflowSendMessageConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/waworkflowapi/provider/WorkflowSendMessageProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/waworkflowapi/provider/service/WorkflowProviderTestConfiguration.java
  src/contractTest/resources/logback-test.xml
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/SendMessageRequest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-271

#273 RWA-706 Enable Fortify in Nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-273

#275 Suppress CVE-2020-23171 until it is fixed
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-275
