Repository hmcts/wa-workflow-api, pull requests merged in 2021-11, with the labels that each got.

#288 RWA-890 [SH] Fixing CVE-2021-22096 by bumping springboot version
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-288

#289 fts fixed
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-289

#290 RWA-776 added ithc and perftest to be in sync with master
  .gitignore
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-290

#292 for CVE-2020-23171 com.nimbusds warning suppressed until 5 Jan
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-292
