Repository hmcts/wa-workflow-api, pull requests merged in 2021-12, with the labels that each got.

#291 feat:Add warning notes to delayed tasks (RWA-772)
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/AddProcessVariableRequest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/Builder.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaProcess.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaProcessVariables.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnValue.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/WarningValues.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/CamundaClient.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/PojoTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/CamundaProcessVariablesTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/DmnValueTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-291

#294 log4j upgraded to 2.15.0
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-294

#296 RWA-1019 [SH] temporarily disabling Fortify from the nightly builds d…
  Jenkinsfile_nightly
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-296
