Repository hmcts/wa-workflow-api, pull requests merged in 2021-07, with the labels that each got.

#250 add fix to address nightly build failure
  security.sh
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-250

#252 Access to new folder in security test report
  security.sh
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-252

#254 Fix nightly build failure
  Jenkinsfile_nightly
  security.sh
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-254

#260 CVE 2021 27568 fix
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-260

#249 Warning external task updated to append warnings
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/Warning.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/WarningValues.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/ExternalTaskWorker.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/WarningTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/WarningValuesTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-249

#262 tomcat cve fix
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-262

#264 Updated warnings task service to support non IAC requirments
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/FeatureToggler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/LaunchDarklyFeatureToggler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/features/FeatureFlag.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/util/LaunchDarklyFeatureTogglerTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-264

#266 Removed feature flag.
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/FeatureToggler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/LaunchDarklyFeatureToggler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/handler/WarningTaskWorkerHandler.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/features/FeatureFlag.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/WarningTaskWorkerHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/util/LaunchDarklyFeatureTogglerTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-266
