Repository hmcts/wa-workflow-api, pull requests merged in 2022-05, with the labels that each got.

#324 Rwa 1349 upgraded postgresql jdbc driver to 42.3.4
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-324

#336 Dependabot configuration changes
  .github/dependabot.yml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-336

#339 RWA-1381: upgraded launchdarkly-java-server-sdk due to CVE-2022-25647
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-339

#358 RWA-1411: tomcat upgrade due to CVE-2022-29885
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-358
