Repository hmcts/wa-workflow-api, pull requests merged in 2022-03, with the labels that each got.

#304 RWA-1142 add clean up helm release into PR stage
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-304

#306 refactor:Supress spring boot vunerabilities
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-306

#305 RWA-982 [SH] Upgrading springboot to 2.6.3 and gradle to 7.3.3
  .github/workflows/swagger.yml
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.properties
  src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/config/OpenAPIPublisherTest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/EvaluateDmnResponse.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/IdempotentKeysRepositoryConfiguration.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/OpenAPIConfiguration.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskController.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/CreateTaskRequest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/ServiceDetails.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/startworkflow/Transition.java
  src/main/resources/application.yaml
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootIntegrationBaseTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-305

#308 RWA-1199 [SH] Upgrading java chart version
  charts/wa-workflow-api/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-308

#310 RWA-1202 [SH] Fixing swagger doc
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-310

#311 RWA-1254 CVE-2020-36518 suppressed
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-311
