Repository hmcts/wa-workflow-api, pull requests merged in 2022-09, with the labels that each got.

#424 RWA-1752
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-424

#422 Merged dependabot upgrades
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-422

#439 Upgraded launchdarkly-java-server-sdk
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-439

#432 Dependabot PRs merge
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-432

#451 CVE-2022-31679, CVE-2022-38751 fixes
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-451
