Repository hmcts/wa-workflow-api, pull requests merged in 2022-04, with the labels that each got.

#313 RWA-1271 Supress postgress CVE
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-313

#314 RWA-1280 - Fix nightly builds - wa-workflow-api
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-314

#316 RWA-1298 - spring boot upgrade to 2.6.6
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-316

#318 RWA-1310 Suppress CVE-2013-4152 and CVE-2013-4152
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-318

#309 RWA-888 refactor errorhandling and return application problem json response
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskControllerTest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdviceBase.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/CallbackControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ErrorMessage.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/FeignApplicationProblemControllerAdvice.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/BadRequestException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/ConflictException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/DatabaseConflictException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/GenericForbiddenException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/GenericServerErrorException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/ResourceNotFoundException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/ServerErrorException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/UnAuthorizedException.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/exceptions/enums/ErrorMessages.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/services/SystemDateProvider.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ApplicationProblemControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/CallbackControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/controllers/advice/ErrorMessageTest.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/services/SystemDateProviderTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-309

#321 RWA-1327: CVE-2016-1000027 supression
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-321

#323 RWA-1333 address CVE-2022-22968 and CVE-2022-22965
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-323

#319 RWA-1098-autoscaling for R1
  charts/wa-workflow-api/Chart.yaml
  charts/wa-workflow-api/values.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-319

#322 RWA-1198-some tests added for supporting wa jurisdiction
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/EndpointSecurityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskControllerTest.java
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/entities/SpecificStandaloneRequest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-322
