Repository hmcts/wa-workflow-api, pull requests merged in 2022-11, with the labels that each got.

#472 RWA-1968 - CVE fixes - upgrade tomcat, springframework boot and springframework security
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-472

#470 RWA 1937
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-470

#469 RWA-1949 Output full jenkins logs
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-469

#489 RWA-2059 - CVE FIX - CVE-2022-41946 - upgrade postgresql 42.5.1
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-489

#485 Updating Chart Version
  charts/wa-workflow-api/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-485
