Repository hmcts/wa-workflow-api, pull requests merged in 2022-10, with the labels that each got.

#456 RWA-1849: Dependabot PRs merge for wa-workflow-api
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-456

#457 RWA-1871: CVE-2022-42003 suppression
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-457

#458 RWA-1852 whitelist task-management-api
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-458
