Repository hmcts/wa-workflow-api, pull requests merged in 2023-01, with the labels that each got.

#493 RWA-2052 Changing after callback to afterSuccess callback
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-493

#488 RWA-2057 Updating Gradle Version to 7.6
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-488

#510 RWA-2132 CVE FIX for wa-workflow-api
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-510

#494 RWA-1955-wa-task-management-api url standardized
  charts/wa-workflow-api/Chart.yaml
  charts/wa-workflow-api/values.yaml
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/TaskManagementServiceApi.java
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-494

#423 RWA-1712
  Dockerfile
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-423

#517 RWA-2044
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/EvaluateDmnTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientService.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/service/TaskClientServiceTest.java
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-517

#524 RWA-2194 Update dependency hashicorp/terraform to v1.3.7
  infrastructure/.terraform-version
Labels: ns:wa, prd:wa, add-or-update, rel:wa-workflow-api-pr-524

#523 RWA-2208 wa-workflow-api - Bump org.owasp.dependencycheck from 7.2.1 ……to 8.0.0
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-523
