Repository hmcts/wa-workflow-api, pull requests merged in 2023-11, with the labels that each got.

#623 Update pact verifier publishResults settings in build.gradle
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-623

#622 Rwa 2918 grant access to reader
  charts/wa-workflow-api/Chart.yaml
  charts/wa-workflow-api/values.preview.template.yaml
  charts/wa-workflow-api/values.yaml
  config/owasp/suppressions.xml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1.0.4__grant_privs_to_reader_user.sql
Labels: ns:wa, prd:wa, enable_keep_helm, rel:wa-workflow-api-pr-622

#626 RWA-2918 Reader User action deletion script
  src/main/resources/db/migration/V1.0.4__grant_privs_to_reader_user.sql
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-626
