Repository hmcts/wa-workflow-api, pull requests merged in 2023-06, with the labels that each got.

#597 RWA-2585: Replace swagger.yml
  .github/workflows/publish-openapi.yml
  .github/workflows/swagger.yml
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/config/OpenAPIConfiguration.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-597

#598 RWA-2591: Update sonar plugin version
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-598

#599 RWA-2601: Address CVE-2023-20883
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-599

#601 RWA-2636: suppress cve
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-601
