Repository hmcts/wa-workflow-api, pull requests merged in 2023-08, with the labels that each got.

#605 Upgrade: java-logging 6.0.1
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-605

#606 RWA-2699: Fix CVE-2020-8908
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-606

#607 Up the java chart version
  charts/wa-workflow-api/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-607
