Repository hmcts/wa-workflow-api, pull requests merged in 2023-02, with the labels that each got.

#527 RWA-2267 Bump launchdarkly-java-server-sdk from 5.10.2 to 6.0.4
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-527

#531 RWA-2259 Update dependency hashicorp/terraform to v1.3.8
  infrastructure/.terraform-version
Labels: ns:wa, prd:wa, add-or-update, rel:wa-workflow-api-pr-531

#534 RWA-2284 Bump org.flywaydb.flyway from 9.4.0 to 9.12.0
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-534

#535 RWA-2285 Bump feign-jackson from 11.10 to 12.1
  build.gradle
Labels: ns:wa, prd:wa, add-or-update, rel:wa-workflow-api-pr-535

#532 RWA-2258 Bump org.sonarqube from 3.4.0.2513 to 3.5.0.2730
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-532

#516 RWA-1868 Enable and fix delay a task test
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/IdempotencyCheckTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/SendMessageTest.java
  src/main/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ActivityInstance.java
  src/test/java/uk/gov/hmcts/reform/waworkflowapi/clients/model/ActivityInstanceTest.java
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-516

#528 RWA-2257 Update Terraform azurerm to v3
  infrastructure/state.tf
Labels: ns:wa, prd:wa, add-or-update, rel:wa-workflow-api-pr-528

#537 RWA-2317 Update Helm release java to v4.0.13
  charts/wa-workflow-api/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-537

#538 RWA-2315 junitPlatform And solidsoft.pitest Update
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-538
