Repository hmcts/wa-workflow-api, pull requests merged in 2024-08, with the labels that each got.

#735 RWA-3473: Gradle V8 upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-735

#756 RWA-3517: Upgrade dependencycheck to 10.0.2
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-756

#771 Nightly dev
  src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/config/RestApiActions.java
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-771
