Repository hmcts/wa-workflow-api, pull requests merged in 2025-04, with the labels that each got.

#868 Amended fortify client dependency
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-868

#867 RWA-4234: re-enable fortify in nightly
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/wa-workflow-api/values.aat.template.yaml
  charts/wa-workflow-api/values.preview.template.yaml
  docker-pactbroker-compose.yml
Labels: ns:wa, prd:wa, enable_fortify_scan, rel:wa-workflow-api-pr-867

#869 Add WA Team as codeowners
  CODEOWNERS
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-869

#870 RWA-3753 - test commit
  README.md
Labels: ns:wa, prd:wa, rel:wa-workflow-api-pr-870
